import type { Lang } from "@/lib/content"

// Pro app copy in English, Urdu and Roman Urdu.
export const T = {
  appSub: { en: "Your day, your route, your safety.", ur: "آپ کا دن، آپ کا راستہ، آپ کی حفاظت۔", ro: "Aapka din, aapka rasta, aapki hifazat." },
  phone: { en: "Mobile number", ur: "موبائل نمبر", ro: "Mobile number" },
  pin: { en: "PIN", ur: "پن", ro: "PIN" },
  login: { en: "Log in", ur: "لاگ ان", ro: "Log in" },
  forgot: { en: "Forgot your PIN? Ask Mjazo ops to reset it.", ur: "پن بھول گئیں؟ مجازو آپریشنز سے نیا پن لیں۔", ro: "PIN bhool gayin? Mjazo ops se naya PIN lein." },
  salaam: { en: "Salaam", ur: "سلام", ro: "Salaam" },
  visits: { en: "visits today", ur: "آج کے وزٹ", ro: "aaj ke visits" },
  noJobs: { en: "No visits assigned for today yet. Ops will add them here.", ur: "آج کے لیے ابھی کوئی وزٹ نہیں۔ آپریشنز یہاں شامل کریں گے۔", ro: "Aaj ke liye abhi koi visit nahi. Ops yahan add karenge." },
  upcoming: { en: "booked for the coming days", ur: "آنے والے دنوں کے لیے بک", ro: "aane wale dinon ke liye book" },
  earned: { en: "Est. earnings · 7 days", ur: "اندازاً کمائی · ۷ دن", ro: "Andazan kamai · 7 din" },
  brief: { en: "Today's brief", ur: "آج کی بریفنگ", ro: "Aaj ki briefing" },
  briefSub: { en: "Your route, customer notes and kit reminders, read aloud.", ur: "آپ کا راستہ، کسٹمر نوٹس اور کٹ کی یاد دہانی، آواز میں۔", ro: "Aapka rasta, customer notes aur kit reminders, awaaz mein." },
  play: { en: "Play", ur: "سنیں", ro: "Sunein" },
  onWay: { en: "On my way", ur: "میں راستے میں ہوں", ro: "Main raste mein hoon" },
  checkIn: { en: "I've arrived · Check in", ur: "پہنچ گئی · چیک اِن", ro: "Pohanch gayi · Check in" },
  finish: { en: "Finish & collect payment", ur: "کام مکمل · ادائیگی", ro: "Kaam mukammal · Payment" },
  map: { en: "Map", ur: "نقشہ", ro: "Map" },
  call: { en: "Call", ur: "کال", ro: "Call" },
  done: { en: "Done", ur: "مکمل", ro: "Mukammal" },
  safeQ: { en: "Are you OK?", ur: "کیا آپ ٹھیک ہیں؟", ro: "Kya aap theek hain?" },
  safeBody: { en: "This visit is running longer than expected. Tap “I'm safe” or check out.", ur: "یہ وزٹ توقع سے لمبا ہو گیا ہے۔ ”میں محفوظ ہوں“ دبائیں یا چیک آؤٹ کریں۔", ro: "Ye visit expected se lamba ho gaya hai. “Main mehfooz hoon” dabayein ya check out karein." },
  safe: { en: "I'm safe", ur: "میں محفوظ ہوں", ro: "Main mehfooz hoon" },
  sos: { en: "SOS", ur: "SOS", ro: "SOS" },
  sosQ: { en: "Send SOS?", ur: "SOS بھیجیں؟", ro: "SOS bhejein?" },
  sosBody: { en: "Mjazo ops get your location at once and will call you. Leave first if you feel unsafe.", ur: "مجازو آپریشنز کو فوراً آپ کی لوکیشن ملے گی اور وہ آپ کو کال کریں گے۔ غیر محفوظ لگے تو پہلے وہاں سے نکلیں۔", ro: "Mjazo ops ko foran aapki location milegi aur woh aapko call karenge. Ghair mehfooz lage to pehle wahan se niklein." },
  sosSend: { en: "Send SOS now", ur: "ابھی SOS بھیجیں", ro: "Abhi SOS bhejein" },
  sosSent: { en: "SOS sent. Ops will call you now. In immediate danger, call 15.", ur: "SOS بھیج دیا گیا۔ آپریشنز ابھی کال کریں گے۔ فوری خطرے میں 15 پر کال کریں۔", ro: "SOS bhej diya. Ops abhi call karenge. Foran khatre mein 15 par call karein." },
  cancel: { en: "Cancel", ur: "منسوخ", ro: "Cancel" },
  close: { en: "Close", ur: "بند کریں", ro: "Band karein" },
  notes: { en: "Customer notes", ur: "کسٹمر نوٹس", ro: "Customer notes" },
  last: { en: "From earlier visits", ur: "پچھلے وزٹ سے", ro: "Pichle visits se" },
  pay: { en: "Collect payment", ur: "ادائیگی وصول کریں", ro: "Payment wasool karein" },
  amount: { en: "Amount received (PKR)", ur: "وصول رقم (روپے)", ro: "Wasool raqam (PKR)" },
  shot: { en: "Add payment screenshot", ur: "ادائیگی کا اسکرین شاٹ لگائیں", ro: "Payment ka screenshot lagayein" },
  shotHint: { en: "AI reads the amount and checks it for you.", ur: "اے آئی رقم پڑھ کر خود چیک کرتا ہے۔", ro: "AI raqam parh kar khud check karta hai." },
  saveFinish: { en: "Save & finish visit", ur: "محفوظ کریں اور وزٹ ختم کریں", ro: "Save karein aur visit khatam karein" },
  copilot: { en: "Copilot", ur: "کو پائلٹ", ro: "Copilot" },
  logout: { en: "Log out", ur: "لاگ آؤٹ", ro: "Log out" },
  min: { en: "min", ur: "منٹ", ro: "min" },
  of: { en: "of", ur: "میں سے", ro: "mein se" },
  total: { en: "Total", ur: "کل", ro: "Total" },
} satisfies Record<string, Record<Lang, string>>
