import { f, type Field, type Fields } from "../fields"
import { register } from "../registry"

// Buttons, labels and messages used across the site (cards, cart, search, forms, checkout, sign-in),
// in English with shipped Urdu. Client components read them with useT(); server components with
// getUi() or <T k="group.key" />. {{tokens}} are filled in where the text is used.

export const UI_DEFAULTS = {
  common: {
    home: "Home",
    available: "Available now",
    live: "Live",
    comingSoon: "Coming soon",
    mostBooked: "Most booked",
    fromPrice: "from {{price}}",
    priceOnRequest: "Price on request",
    quote: "Quote",
    add: "Add",
    added: "Added",
    options: "Options",
    chooseOptions: "Choose options",
    view: "View",
    notifyMe: "Notify me",
    faqTitle: "Questions, answered",
    close: "Close",
    total: "Total",
    visitFee: "Visit fee",
    free: "Free",
    language: "اردو",
    languageName: "English",
  },
  duration: { flexible: "Flexible", min: "{{m}} min", hr: "{{h}} hr", hrs: "{{h}} hrs", hrMin: "{{h}} hr {{m}} min", today: "Today", tomorrow: "Tomorrow" },
  pro: { women: "Women-only pros", technician: "Verified technicians", care: "Licensed & verified carers" },
  crumbs: {
    services: "Services",
    help: "Help",
    areas: "Areas",
    weddings: "Weddings & events",
    report: "Report a problem",
    refer: "Refer & earn",
    rate: "Rate your visit",
    offers: "Offers",
    plus: "Mjazo Plus",
    journal: "Journal",
    homePulse: "Home Pulse",
    giftCards: "Gift cards",
    gharScan: "Ghar Scan",
    app: "Get the app",
    contact: "Contact",
    careers: "Careers",
    about: "About",
    business: "Mjazo for Business",
    safety: "Safety & trust",
    howItWorks: "How it works",
  },
  cart: {
    title: "Your cart",
    sub: "Prices are all-in. Pay after the service.",
    empty: "Nothing here yet.",
    browse: "Browse beauty",
    viewCart: "View cart",
    viewCartArrow: "View cart →",
    checkout: "Checkout",
    minReached: "Minimum order reached. Nice.",
    addMore: "Add {{amount}} more to reach the {{min}} minimum per visit.",
    item: "{{count}} item",
    items: "{{count}} items",
    decrease: "Decrease",
    increase: "Increase",
    remove: "Remove",
  },
  search: {
    title: "Search services",
    placeholder: "Search waxing, facial, AC service…",
    popular: "Popular",
    popularTerms: ["Full body waxing", "Brightening facial", "Party makeup", "Mani-pedi", "AC service", "Deep cleaning", "Mehndi"],
    noMatch: "No match for “{{q}}”.",
    askAi: "Ask Mjazo AI",
    or: "or",
    browseAll: "browse all services",
  },
  location: {
    title: "Where should we come?",
    sub: "We come to {{count}} neighbourhoods across Karachi. Pick yours, then your sub-area.",
    pickSub: "Pick your {{area}} sub-area",
    notYet: "We're not in *{{area}}* yet. Join the list and we'll WhatsApp you the day we open.",
  },
  notify: {
    name: "Your name",
    phone: "WhatsApp number",
    area: "Your area",
    done: "You're on the list. We'll WhatsApp you when we open.",
    errPhone: "Enter a Pakistani mobile number, e.g. 0300 1234567",
    errArea: "Pick your area",
  },
  form: {
    name: "Your name",
    phone: "WhatsApp number",
    email: "Email (optional)",
    message: "Anything else? (optional)",
    send: "Send enquiry",
    successTitle: "Got it, thank you.",
    successBody: "We'll WhatsApp you within working hours.",
    preferWhatsapp: "Prefer WhatsApp?",
    choose: "Choose…",
    required: "Required",
    errName: "Please enter your name",
    errEmail: "Check your email address",
  },
  menu: {
    under2k: "Under PKR 2,000",
    under1h: "Under 1 hour",
    hasOptions: "Has options",
    sort: "Sort",
    sortPopular: "Most booked",
    sortPriceAsc: "Price: low to high",
    sortPriceDesc: "Price: high to low",
    sortQuickest: "Quickest first",
    optionsAvailable: "Options available",
    none: "Nothing matches those filters.",
    clear: "Clear filters",
  },
  purchase: {
    pricedToNeeds: "Priced to your needs",
    quoteBody: "Tell us your dates and what you need. We'll match you with the right pro and send a fixed quote.",
    quoteMessage: "Hi Mjazo! I'd like a quote for {{service}}.",
    quoteCta: "Get a quote on WhatsApp",
    notLive: "{{service}} isn't live in your area yet. Join the waitlist and we'll WhatsApp you the day it opens.",
    allIn: "All-in price",
    included: "Included",
    addOns: "Add-ons",
    people: "People",
    fewer: "Fewer",
    more: "More",
    addToCart: "Add to cart",
    addedToCart: "Added to cart",
    bookNow: "Book now",
    minNote: "Minimum per visit is {{min}}. Add another service or try a bundle.",
    bookMessage: "Hi Mjazo! I'd like to book {{service}}.",
    preferWhatsapp: "Prefer to book on WhatsApp?",
  },
  checkout: {
    cash: "Cash",
    cashSub: "Pay your pro after the service",
    sendAfter: "Send after the service",
    raastSub: "Instant bank transfer after",
    errArea: "Choose your area",
    errAddress: "Add your house number and street",
    errDate: "Pick a date",
    errWindow: "Pick a time window",
    errName: "Enter your name",
    errMin: "Minimum per visit is {{min}}",
    emptyTitle: "Your cart is empty",
    emptyBody: "Add a service first, then come back to book a time.",
    emptyCta: "Browse Beauty & Wellness",
    where: "Where should we come?",
    area: "Area",
    elsewhere: "Somewhere else?",
    subArea: "{{area}} sub-area",
    address: "House no. & street",
    addressHint: "e.g. 24-C, Khayaban-e-Ittehad",
    landmark: "Landmark (optional)",
    landmarkHint: "Near…",
    when: "When suits you?",
    window: "Arrival window",
    windowNote: "Your pro arrives within the window. Free changes up to {{hours}} hours before.",
    who: "Who are we visiting?",
    phoneHint: "We'll confirm your booking here.",
    briefScan: "Ghar Scan brief for your technician",
    briefLook: "Look Card for your pro",
    sendBrief: "Send it to my pro (photos are deleted after the visit)",
    sendBriefPhotos: "Send it with {{count}} photo(s) to my pro (photos are deleted after the visit)",
    notes: "Notes for your pro (optional)",
    notesHint: "Allergies, a favourite pro, parking tips…",
    pay: "How will you pay?",
    payMethod: "Payment method",
    nothingNow: "Nothing to pay now. You pay after your service, once you're happy.",
    summary: "Your booking",
    friendWelcome: "Friend's welcome ({{code}})",
    confirm: "Confirm booking",
    booking: "Booking…",
    agree: "By confirming you agree to our {{terms}} and {{cancellation}}.",
    terms: "terms",
    cancellation: "cancellation policy",
    chatBold: "Prefer to chat?",
    chatText: "Send this cart to us on WhatsApp and we'll book it for you.",
    trust: "Women-only beauty pros · CNIC-verified · Sealed kits",
    totalPayAfter: "Total · pay after",
    waIntro: "Hi Mjazo! I'd like to book:",
  },
  confirmation: {
    booked: "You're booked.",
    bookedName: "You're booked, {{name}}.",
    confirmShortly: "We'll confirm on WhatsApp shortly. Booking reference {{ref}}",
    when: "When",
    where: "Where",
    payAfter: "Pay after",
    addCalendar: "Add to calendar",
    confirmWa: "Confirm on WhatsApp",
    myBookings: "My bookings",
    nextTitle: "What happens next",
    next: [
      { title: "Confirmed on WhatsApp", body: "Within working hours, we confirm your booking and slot." },
      { title: "Your pro is assigned", body: "You'll get her first name and photo before the visit." },
      { title: "Live check-in", body: "She checks in on arrival and opens a sealed kit in front of you." },
      { title: "Pay after, then rate", body: "Pay the way you chose. Loved it? Rebook her in one tap." },
    ],
  },
  cartPage: {
    emptyTitle: "Nothing here yet",
    emptyBody: "Start with a favourite. It takes two minutes.",
    addMoreFrom: "Add more from {{category}}",
    clear: "Clear cart",
    chooseTime: "Choose a time",
    payNote: "Pay after your service. Free changes up to {{hours}} hours before.",
    addSomething: "Add something?",
  },
  login: {
    tagline: "Ghar ka har kaam. Pakka.",
    taglineSub: "Your bookings, saved details and one-tap rebooking, in one place.",
    title: "Welcome to Mjazo",
    sub: "Sign in with your name and number. No passwords, nothing to remember.",
    phone: "Mobile / WhatsApp number",
    continue: "Continue",
    legal: "Your profile is saved on this device and we confirm every booking on WhatsApp. By continuing you agree to our {{terms}} and {{privacy}}.",
    terms: "terms",
    privacy: "privacy policy",
  },
}

export type UiStrings = typeof UI_DEFAULTS

/** Hand-written Urdu for every string above (reviewed copy; edit in Navigation → Buttons & labels). */
export const UI_UR: UiStrings = {
  common: {
    home: "ہوم",
    available: "ابھی دستیاب",
    live: "دستیاب",
    comingSoon: "جلد آ رہا ہے",
    mostBooked: "سب سے زیادہ بُک",
    fromPrice: "{{price}} سے شروع",
    priceOnRequest: "قیمت درخواست پر",
    quote: "کوٹ",
    add: "شامل کریں",
    added: "شامل ہو گیا",
    options: "آپشنز",
    chooseOptions: "آپشنز منتخب کریں",
    view: "دیکھیں",
    notifyMe: "مجھے بتائیں",
    faqTitle: "آپ کے سوالات کے جواب",
    close: "بند کریں",
    total: "کُل",
    visitFee: "وزٹ فیس",
    free: "مفت",
    language: "English",
    languageName: "اردو",
  },
  duration: { flexible: "حسبِ ضرورت", min: "{{m}} منٹ", hr: "{{h}} گھنٹہ", hrs: "{{h}} گھنٹے", hrMin: "{{h}} گھنٹہ {{m}} منٹ", today: "آج", tomorrow: "کل" },
  pro: { women: "صرف خواتین پروز", technician: "تصدیق شدہ ٹیکنیشنز", care: "لائسنس یافتہ اور تصدیق شدہ نگہداشت کار" },
  crumbs: {
    services: "سروسز",
    help: "مدد",
    areas: "علاقے",
    weddings: "شادیاں اور تقریبات",
    report: "مسئلہ رپورٹ کریں",
    refer: "ریفر کریں اور کمائیں",
    rate: "اپنے وزٹ کی ریٹنگ دیں",
    offers: "آفرز",
    plus: "مجازو پلس",
    journal: "جرنل",
    homePulse: "ہوم پلس",
    giftCards: "گفٹ کارڈز",
    gharScan: "گھر اسکین",
    app: "ایپ حاصل کریں",
    contact: "رابطہ",
    careers: "کیریئرز",
    about: "ہمارے بارے میں",
    business: "مجازو فار بزنس",
    safety: "حفاظت اور اعتماد",
    howItWorks: "یہ کیسے کام کرتا ہے",
  },
  cart: {
    title: "آپ کی کارٹ",
    sub: "قیمت میں سب کچھ شامل ہے۔ ادائیگی سروس کے بعد۔",
    empty: "ابھی یہاں کچھ نہیں۔",
    browse: "بیوٹی سروسز دیکھیں",
    viewCart: "کارٹ دیکھیں",
    viewCartArrow: "کارٹ دیکھیں ←",
    checkout: "چیک آؤٹ",
    minReached: "کم از کم آرڈر پورا ہو گیا۔ بہت خوب۔",
    addMore: "ہر وزٹ کے کم از کم {{min}} تک پہنچنے کے لیے مزید {{amount}} کی سروس شامل کریں۔",
    item: "{{count}} آئٹم",
    items: "{{count}} آئٹمز",
    decrease: "کم کریں",
    increase: "بڑھائیں",
    remove: "ہٹائیں",
  },
  search: {
    title: "سروسز تلاش کریں",
    placeholder: "ویکسنگ، فیشل، اے سی سروس تلاش کریں…",
    popular: "مقبول",
    popularTerms: ["فل باڈی ویکسنگ", "برائٹننگ فیشل", "پارٹی میک اپ", "مینی پیڈی", "اے سی سروس", "ڈیپ کلیننگ", "مہندی"],
    noMatch: "“{{q}}” سے کچھ نہیں ملا۔",
    askAi: "مجازو اے آئی سے پوچھیں",
    or: "یا",
    browseAll: "تمام سروسز دیکھیں",
  },
  location: {
    title: "ہم کہاں آئیں؟",
    sub: "ہم کراچی کے {{count}} علاقوں میں آتے ہیں۔ اپنا علاقہ چنیں، پھر اپنا سیکٹر۔",
    pickSub: "{{area}} میں اپنا سیکٹر چنیں",
    notYet: "ہم ابھی *{{area}}* میں نہیں ہیں۔ فہرست میں نام لکھوائیں، جس دن ہم وہاں شروع کریں گے آپ کو واٹس ایپ کر دیں گے۔",
  },
  notify: {
    name: "آپ کا نام",
    phone: "واٹس ایپ نمبر",
    area: "آپ کا علاقہ",
    done: "آپ فہرست میں شامل ہیں۔ ہم شروع کرتے ہی آپ کو واٹس ایپ کریں گے۔",
    errPhone: "پاکستانی موبائل نمبر درج کریں، مثلاً 0300 1234567",
    errArea: "اپنا علاقہ چنیں",
  },
  form: {
    name: "آپ کا نام",
    phone: "واٹس ایپ نمبر",
    email: "ای میل (اختیاری)",
    message: "کچھ اور بتانا چاہیں گے؟ (اختیاری)",
    send: "انکوائری بھیجیں",
    successTitle: "مل گیا، شکریہ۔",
    successBody: "ہم کام کے اوقات میں آپ کو واٹس ایپ کریں گے۔",
    preferWhatsapp: "واٹس ایپ پر بات کرنا پسند ہے؟",
    choose: "منتخب کریں…",
    required: "ضروری ہے",
    errName: "براہِ کرم اپنا نام لکھیں",
    errEmail: "اپنا ای میل ایڈریس چیک کریں",
  },
  menu: {
    under2k: "PKR 2,000 سے کم",
    under1h: "ایک گھنٹے سے کم",
    hasOptions: "آپشنز کے ساتھ",
    sort: "ترتیب",
    sortPopular: "سب سے زیادہ بُک",
    sortPriceAsc: "قیمت: کم سے زیادہ",
    sortPriceDesc: "قیمت: زیادہ سے کم",
    sortQuickest: "کم وقت والی پہلے",
    optionsAvailable: "آپشنز دستیاب",
    none: "ان فلٹرز سے کچھ نہیں ملا۔",
    clear: "فلٹرز ہٹائیں",
  },
  purchase: {
    pricedToNeeds: "آپ کی ضرورت کے مطابق قیمت",
    quoteBody: "ہمیں اپنی تاریخیں اور ضرورت بتائیں۔ ہم آپ کے لیے صحیح پرو چنیں گے اور طے شدہ قیمت بھیجیں گے۔",
    quoteMessage: "السلام علیکم مجازو! مجھے {{service}} کی قیمت معلوم کرنی ہے۔",
    quoteCta: "واٹس ایپ پر قیمت معلوم کریں",
    notLive: "{{service}} ابھی آپ کے علاقے میں دستیاب نہیں۔ ویٹ لسٹ میں نام لکھوائیں، شروع ہوتے ہی ہم آپ کو واٹس ایپ کریں گے۔",
    allIn: "مکمل قیمت",
    included: "شامل",
    addOns: "اضافی سروسز",
    people: "افراد",
    fewer: "کم",
    more: "زیادہ",
    addToCart: "کارٹ میں شامل کریں",
    addedToCart: "کارٹ میں شامل ہو گیا",
    bookNow: "ابھی بُک کریں",
    minNote: "ہر وزٹ کے لیے کم از کم {{min}}۔ ایک اور سروس شامل کریں یا کوئی بنڈل آزمائیں۔",
    bookMessage: "السلام علیکم مجازو! میں {{service}} بُک کرنا چاہتی/چاہتا ہوں۔",
    preferWhatsapp: "واٹس ایپ پر بُک کرنا پسند ہے؟",
  },
  checkout: {
    cash: "نقد",
    cashSub: "سروس کے بعد اپنے پرو کو ادائیگی کریں",
    sendAfter: "سروس کے بعد بھیجیں",
    raastSub: "سروس کے بعد فوری بینک ٹرانسفر",
    errArea: "اپنا علاقہ چنیں",
    errAddress: "گھر نمبر اور گلی لکھیں",
    errDate: "تاریخ چنیں",
    errWindow: "وقت چنیں",
    errName: "اپنا نام لکھیں",
    errMin: "ہر وزٹ کے لیے کم از کم {{min}}",
    emptyTitle: "آپ کی کارٹ خالی ہے",
    emptyBody: "پہلے کوئی سروس شامل کریں، پھر وقت بُک کرنے کے لیے واپس آئیں۔",
    emptyCta: "بیوٹی اینڈ ویلنیس دیکھیں",
    where: "ہم کہاں آئیں؟",
    area: "علاقہ",
    elsewhere: "کہیں اور؟",
    subArea: "{{area}} کا سیکٹر",
    address: "گھر نمبر اور گلی",
    addressHint: "مثلاً 24-C، خیابانِ اتحاد",
    landmark: "قریبی نشانی (اختیاری)",
    landmarkHint: "کے قریب…",
    when: "آپ کے لیے کب مناسب ہے؟",
    window: "آمد کا وقت",
    windowNote: "آپ کا پرو اسی وقت کے اندر پہنچے گا۔ وقت سے {{hours}} گھنٹے پہلے تک تبدیلی مفت ہے۔",
    who: "ہم کس کے پاس آ رہے ہیں؟",
    phoneHint: "ہم یہیں آپ کی بُکنگ کنفرم کریں گے۔",
    briefScan: "آپ کے ٹیکنیشن کے لیے گھر اسکین بریف",
    briefLook: "آپ کے پرو کے لیے لُک کارڈ",
    sendBrief: "یہ میرے پرو کو بھیج دیں (وزٹ کے بعد تصاویر ڈیلیٹ ہو جاتی ہیں)",
    sendBriefPhotos: "یہ {{count}} تصاویر کے ساتھ میرے پرو کو بھیج دیں (وزٹ کے بعد تصاویر ڈیلیٹ ہو جاتی ہیں)",
    notes: "پرو کے لیے ہدایات (اختیاری)",
    notesHint: "الرجی، پسندیدہ پرو، پارکنگ کی معلومات…",
    pay: "آپ کیسے ادائیگی کریں گے؟",
    payMethod: "ادائیگی کا طریقہ",
    nothingNow: "ابھی کچھ ادا نہیں کرنا۔ سروس کے بعد، مطمئن ہونے پر ادائیگی کریں۔",
    summary: "آپ کی بُکنگ",
    friendWelcome: "دوست کی طرف سے خوش آمدید ({{code}})",
    confirm: "بُکنگ کنفرم کریں",
    booking: "بُک ہو رہا ہے…",
    agree: "کنفرم کر کے آپ ہماری {{terms}} اور {{cancellation}} سے اتفاق کرتے ہیں۔",
    terms: "شرائط",
    cancellation: "منسوخی کی پالیسی",
    chatBold: "چیٹ کرنا پسند ہے؟",
    chatText: "یہ کارٹ ہمیں واٹس ایپ پر بھیجیں، ہم آپ کے لیے بُک کر دیں گے۔",
    trust: "صرف خواتین بیوٹی پروز · شناختی کارڈ سے تصدیق شدہ · سیل بند کٹس",
    totalPayAfter: "کُل · بعد میں ادائیگی",
    waIntro: "السلام علیکم مجازو! میں یہ بُک کرنا چاہتی/چاہتا ہوں:",
  },
  confirmation: {
    booked: "آپ کی بُکنگ ہو گئی۔",
    bookedName: "{{name}}، آپ کی بُکنگ ہو گئی۔",
    confirmShortly: "ہم جلد ہی واٹس ایپ پر کنفرم کریں گے۔ بُکنگ نمبر {{ref}}",
    when: "کب",
    where: "کہاں",
    payAfter: "بعد میں ادائیگی",
    addCalendar: "کیلنڈر میں شامل کریں",
    confirmWa: "واٹس ایپ پر کنفرم کریں",
    myBookings: "میری بُکنگز",
    nextTitle: "آگے کیا ہوگا",
    next: [
      { title: "واٹس ایپ پر تصدیق", body: "کام کے اوقات میں ہم آپ کی بُکنگ اور وقت کنفرم کرتے ہیں۔" },
      { title: "آپ کا پرو مقرر", body: "وزٹ سے پہلے آپ کو ان کا نام اور تصویر مل جائے گی۔" },
      { title: "لائیو چیک اِن", body: "پہنچ کر وہ چیک اِن کرتی ہیں اور آپ کے سامنے سیل بند کٹ کھولتی ہیں۔" },
      { title: "بعد میں ادائیگی، پھر ریٹنگ", body: "اپنے منتخب طریقے سے ادائیگی کریں۔ پسند آیا؟ ایک ٹیپ میں دوبارہ بُک کریں۔" },
    ],
  },
  cartPage: {
    emptyTitle: "ابھی یہاں کچھ نہیں",
    emptyBody: "کسی پسندیدہ سروس سے شروع کریں۔ صرف دو منٹ لگتے ہیں۔",
    addMoreFrom: "{{category}} سے مزید شامل کریں",
    clear: "کارٹ خالی کریں",
    chooseTime: "وقت چنیں",
    payNote: "ادائیگی سروس کے بعد۔ وقت سے {{hours}} گھنٹے پہلے تک تبدیلی مفت ہے۔",
    addSomething: "کچھ اور شامل کریں؟",
  },
  login: {
    tagline: "گھر کا ہر کام۔ پکا۔",
    taglineSub: "آپ کی بُکنگز، محفوظ تفصیلات اور ایک ٹیپ میں دوبارہ بُکنگ، سب ایک جگہ۔",
    title: "مجازو میں خوش آمدید",
    sub: "اپنے نام اور نمبر سے سائن اِن کریں۔ نہ پاس ورڈ، نہ کچھ یاد رکھنا۔",
    phone: "موبائل / واٹس ایپ نمبر",
    continue: "جاری رکھیں",
    legal: "آپ کی پروفائل اسی ڈیوائس پر محفوظ رہتی ہے اور ہم ہر بُکنگ واٹس ایپ پر کنفرم کرتے ہیں۔ جاری رکھ کر آپ ہماری {{terms}} اور {{privacy}} سے اتفاق کرتے ہیں۔",
    terms: "شرائط",
    privacy: "پرائیویسی پالیسی",
  },
}

// ---------------------------------------------------------------------------
// Fields, generated from the defaults (one group per area of the site)
// ---------------------------------------------------------------------------

const GROUPS: Record<keyof UiStrings, string> = {
  common: "Everywhere",
  duration: "Durations and days",
  pro: "Pro types",
  crumbs: "Breadcrumb section names",
  cart: "Cart",
  search: "Search",
  location: "Area picker",
  notify: "Waitlist form",
  form: "Enquiry forms",
  menu: "Category menu",
  purchase: "Service booking box",
  checkout: "Checkout",
  confirmation: "Booking confirmed",
  cartPage: "Cart page",
  login: "Sign in",
}
const label = (key: string) => key.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase())
function fieldFor(key: string, v: unknown): Field {
  if (Array.isArray(v)) {
    if (typeof v[0] === "string") return f.list(label(key), f.text("Item"))
    const first = v[0] as Record<string, string>
    return f.list(label(key), f.group("Item", Object.fromEntries(Object.keys(first).map((k) => [k, f.text(label(k))]))), { itemLabel: Object.keys(first)[0] })
  }
  const s = String(v)
  const tokens = s.match(/\{\{\w+\}\}/g)
  return f.text(label(key), { help: [`“${s}”`, tokens ? `Keep ${[...new Set(tokens)].join(", ")}.` : "", s.includes("*") ? "*Stars* make words bold." : ""].filter(Boolean).join(" ") })
}
const fields: Fields = Object.fromEntries(
  (Object.keys(UI_DEFAULTS) as (keyof UiStrings)[]).map((g) => [g, f.group(GROUPS[g], Object.fromEntries(Object.entries(UI_DEFAULTS[g]).map(([k, v]) => [k, fieldFor(k, v)])))]),
)

register<UiStrings, UiStrings>({
  type: "ui",
  label: "Buttons & labels",
  group: "Navigation",
  kind: "singleton",
  icon: "Tag",
  description: "Small text used across the site: cards, cart, search, forms, checkout and sign-in. Each field shows the original English under its name.",
  fields,
  defaults: () => UI_DEFAULTS,
  translations: { ur: () => UI_UR },
  path: () => "/checkout",
})
